image: ghcr.io/zephyrproject-rtos/ci:v0.28.6
stages:
  - build

variables:
  SCALENODE_RAM: 4096
  SCALENODE_DISK: 10
  DEBIAN_FRONTEND: noninteractive
  ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains


build:
  stage: build
  parallel: [native_sim/native/64, stm32h747i_disco/stm32h747xx/m7]
  script:
    - west init -l .
    - west update
    - west patch apply
    - west build -b ${CI_PARALLEL_NAME}
    - PLATFORM=$(echo "$CI_PARALLEL_NAME" | cut -d/ -f1)
    - mv build/zephyr/zephyr.elf build/zephyr/zephyr-$PLATFORM-grvl-calendar.elf
    - mv build/zephyr/zephyr.sdcard.img build/zephyr/zephyr-$PLATFORM-grvl-calendar.sdcard.img || true
  artifacts:
    paths:
      - romfs
      - build/zephyr/zephyr*
