CONFIG_INPUT=y
CONFIG_INPUT_QUEUE_MAX_MSGS=128
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_DISPLAY=y
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_STD_CPP23=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CPP_RTTI=y
CONFIG_POSIX_FILE_SYSTEM=y
CONFIG_LOG_MODE_DEFERRED=y
# CONFIG_LOG_PRINTK is not set
CONFIG_LOG_INFO_COLOR_GREEN=y
